### ISSUE TITLE
Support Terragrunt HCL out of the box

### ISSUE THREAD

**Issue by kholisrag** [gamunu/vscode-opentofu#41]
### Extension Version

v0.1.1

### Problem Statement

I need to have format on save for `terragrunt.hcl`

currently I can do it but the syntax causing many problems reported
![2024-04-08_13-12](https://github.com/gamunu/vscode-opentofu/assets/4683704/ee823c09-1fd3-4422-9290-8636dbacdf26)

### Expected User Experience

out of the box support terragrunt syntax and able to do format on save

### Proposal

add terragrunt schema to the opentofu for `terragrunt.hcl` file or `*.hcl`

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by gamunu** [comment]
@kholisrag  We cannot implement the language server enhancement you requested due to limited resources, but we may consider it as a potential feature improvement. However, we cannot guarantee its inclusion in this extension.

However, you can utilize the Terraform HCL extension for syntax highlighting and formatting support for Terragrunt.

https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL
